### ISSUE TITLE
Improved login

### ISSUE THREAD

**Issue by carolynvs** [getporter/az-mixin#33]
Logging in is a pain right now. You have to specify it for each action, and pass in a bunch of flags and remember to suppress output:

```yaml
- az: 
      description: "Logging into Azure..."  
      arguments:
        - login
      flags:
        service-principal: ""
        username: "'{{bundle.credentials.AZURE_CLIENT_ID}}'"
        password: "'{{bundle.credentials.AZURE_CLIENT_SECRET}}'"
        tenant: "'{{bundle.credentials.AZURE_TENANT_ID}}'"
      suppress-output: true
```

We could add a custom login command to the mixin to simplify the default login, which assumes the default environment variable names:

```yaml
install:
- az:
     login:
```

In addition, we could have the mixin detect if we are logged in (a file gets stored in ~/.azure after login) before running a command and then automatically logging in if needed.
